import fs from "node:fs/promises";
import path from "node:path";

export interface ManagedBrowserScenarioStep {
  id: string;
  type: string;
  enabled?: boolean;
  [key: string]: unknown;
}

export interface ManagedBrowserScenario {
  id: string;
  name: string;
  baseUrl: string;
  description?: string;
  viewport?: {
    width: number;
    height: number;
  };
  steps: ManagedBrowserScenarioStep[];
  [key: string]: unknown;
}

export interface CreateScenarioInput {
  id: string;
  name: string;
  baseUrl: string;
  force?: boolean;
}

export interface AddStepInput {
  scenarioId: string;
  step: ManagedBrowserScenarioStep;
}

export class BrowserScenarioManager {
  constructor(private readonly scenarioDir = path.join(process.cwd(), "browser-scenarios")) {}

  async list(): Promise<string[]> {
    await fs.mkdir(this.scenarioDir, { recursive: true });
    const entries = await fs.readdir(this.scenarioDir, { withFileTypes: true });

    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
      .map((entry) => entry.name.replace(/\.json$/, ""))
      .sort();
  }

  async create(input: CreateScenarioInput): Promise<string> {
    await fs.mkdir(this.scenarioDir, { recursive: true });

    const filePath = this.resolveScenarioPath(input.id);

    if (!input.force && await fileExists(filePath)) {
      throw new Error(`Scenario already exists: ${input.id}. Use --force to overwrite.`);
    }

    const scenario: ManagedBrowserScenario = {
      id: input.id,
      name: input.name,
      baseUrl: input.baseUrl,
      description: "Managed browser scenario generated by NusaTestLab.",
      viewport: {
        width: 1365,
        height: 768
      },
      steps: [
        {
          id: "open-homepage",
          type: "goto",
          enabled: true,
          path: "/"
        }
      ]
    };

    await this.save(filePath, scenario);
    return filePath;
  }

  async load(scenarioId: string): Promise<ManagedBrowserScenario> {
    const filePath = this.resolveScenarioPath(scenarioId);
    const raw = await fs.readFile(filePath, "utf-8");
    return JSON.parse(raw.replace(/^\uFEFF/, "")) as ManagedBrowserScenario;
  }

  async addStep(input: AddStepInput): Promise<ManagedBrowserScenario> {
    const filePath = this.resolveScenarioPath(input.scenarioId);
    const scenario = await this.load(input.scenarioId);

    if (!Array.isArray(scenario.steps)) {
      scenario.steps = [];
    }

    if (scenario.steps.some((step) => step.id === input.step.id)) {
      throw new Error(`Step already exists: ${input.step.id}`);
    }

    scenario.steps.push(input.step);
    await this.save(filePath, scenario);
    return scenario;
  }

  async setStepEnabled(scenarioId: string, stepId: string, enabled: boolean): Promise<ManagedBrowserScenario> {
    const filePath = this.resolveScenarioPath(scenarioId);
    const scenario = await this.load(scenarioId);
    const step = scenario.steps.find((item) => item.id === stepId);

    if (!step) {
      throw new Error(`Step not found: ${stepId}`);
    }

    step.enabled = enabled;
    await this.save(filePath, scenario);
    return scenario;
  }

  async deleteStep(scenarioId: string, stepId: string): Promise<ManagedBrowserScenario> {
    const filePath = this.resolveScenarioPath(scenarioId);
    const scenario = await this.load(scenarioId);
    const before = scenario.steps.length;

    scenario.steps = scenario.steps.filter((step) => step.id !== stepId);

    if (scenario.steps.length === before) {
      throw new Error(`Step not found: ${stepId}`);
    }

    await this.save(filePath, scenario);
    return scenario;
  }

  resolveScenarioPath(scenarioId: string): string {
    const safeId = scenarioId.replace(/\.json$/, "");
    return path.join(this.scenarioDir, `${safeId}.json`);
  }

  private async save(filePath: string, scenario: ManagedBrowserScenario): Promise<void> {
    await fs.writeFile(filePath, `${JSON.stringify(scenario, null, 2)}\n`, "utf-8");
  }
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
