import { Command } from "commander";
import chalk from "chalk";
import { ProfileScaffolder } from "../profile-scaffolding/profile-scaffolder.js";

export function registerProfileCreateCommand(program: Command): void {
  program
    .command("profile:create")
    .description("Create a new SaaS testing profile scaffold.")
    .argument("<profileName>", "Profile name in kebab-case. Example: clinic-saas")
    .option("--display-name <name>", "Display name for the profile.")
    .option("--description <description>", "Profile description.")
    .option("--roles <roles>", "Comma-separated roles.", "owner,admin,member")
    .option("--modules <modules>", "Comma-separated modules.", "api,auth,roles,security,performance")
    .option("--overwrite", "Overwrite existing scaffold files.", false)
    .action(
      async (
        profileName: string,
        options: {
          displayName?: string;
          description?: string;
          roles: string;
          modules: string;
          overwrite: boolean;
        }
      ) => {
        const displayName = options.displayName ?? toDisplayName(profileName);
        const description =
          options.description ??
          `Testing profile for ${displayName}. Generated by NusaTestLab profile scaffolder.`;

        const roles = splitCsv(options.roles);
        const modules = splitCsv(options.modules);

        try {
          const scaffolder = new ProfileScaffolder();
          const result = await scaffolder.create({
            profileName,
            displayName,
            description,
            roles,
            modules,
            overwrite: options.overwrite
          });

          console.log(chalk.bold("\nNusaTestLab Profile Scaffold Created"));
          console.log("-------------------------------------");
          console.log(`Profile     : ${profileName}`);
          console.log(`Display Name: ${displayName}`);
          console.log(`Directory   : ${result.profileDir}`);
          console.log("");

          console.log(chalk.green("Created Files:"));
          if (result.createdFiles.length === 0) {
            console.log("  - none");
          } else {
            for (const file of result.createdFiles) {
              console.log(`  - ${file}`);
            }
          }

          if (result.skippedFiles.length > 0) {
            console.log("");
            console.log(chalk.yellow("Skipped Files:"));
            for (const file of result.skippedFiles) {
              console.log(`  - ${file}`);
            }
            console.log("");
            console.log(chalk.gray("Use --overwrite to replace existing files."));
          }

          console.log("");
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          console.error(chalk.red("Failed to create profile scaffold."));
          console.error(chalk.red(message));
          process.exit(1);
        }
      }
    );
}

function splitCsv(value: string): string[] {
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function toDisplayName(profileName: string): string {
  return profileName
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
